version: '3.8'

services:
  database:
    image: mysql:8
    container_name: processes-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=processes
    networks:
      - db

  api:
    build: ./api
    container_name: processes-api
    restart: on-failure
    depends_on:
      - database
    networks:
      - db

networks:
  db:
