--liquibase formatted sql

--changeset reginaldo:1587663728087-01
CREATE TABLE users (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, email VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL);

--changeset reginaldo:1587663728087-02
CREATE TABLE userPermissions (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  type ENUM('ADMIN', 'TRIATOR', 'FINISHER') NOT NULL, 
  userId INT NOT NULL, 
  CONSTRAINT FK_USER_PERMISSIONS_USER_ID FOREIGN KEY (userId) REFERENCES users(id)
);

--changeset reginaldo:1587663728087-03
CREATE TABLE processes (id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, description TEXT);

--changeset reginaldo:1587663728087-04
CREATE TABLE processFinishers (
  processId INT NOT NULL, 
  userId INT NOT NULL, 
  CONSTRAINT FK_PROCESS_FINISHERS_PROCESS_ID FOREIGN KEY (processId) REFERENCES processes(id),
  CONSTRAINT FK_PROCESS_FINISHERS_USER_ID FOREIGN KEY (userId) REFERENCES users(id)
);


